export const ENTER_KEY = 'Enter'
export const TYPE_STRING = 'string'
export const ADD_FAVOURITE = 'add'
export const REMOVE_FAVOURITE = 'remove'
export const SEARCH_DEBOUNCE_TIMER = 1000
export const GENERAL_ERROR = 'An error occured'
export const ABORTED_ERROR = 'aborted'
export const LONGEST_MOVIE_TITLE_LENGTH = 191
export const IMAGE_INTRINSIC_WIDTH = 500
export const IMAGE_INTRINSIC_HEIGHT = 281